paths:
  path to initial model weights: null

data loading:
  dataset: MNIST grid
  batch size: 4

optimizer:
  epochs: 2000
  checkpoint frequency: 10
  validation frequency: 10
  learning rate: 2e-5
  scheduler type: null
  # accepts null, exponential, reduce on plateau

phase 1 end: 50
phase 2 end: 200
number of refinements: 0

loss:
  weights:
    relation sparsity: .1
    relation smooth: .1
    # relation score: 1.
    # cross entropy: 1.
    init guess weight: 1.

network:
  type: patch
  number of heads: 12
  relation kernel size: 13
  number of relations: 32
  patch size: 7,7
  segmenter architecture:
    channels by depth: 1,64,64,128,64,N_L
    kernels by depth: 7,1,5,3,3
    pool depths: 1
  PatchTemplate HPs:
    channels by depth: 1,64,64,N_L*N_V
    kernels by depth: 3,1,3

random seed: 0
fixed input size: True
