paths:
  path to initial model weights: null

data loading:
  dataset: MNIST grid
  batch size: 16

optimizer:
  epochs: 50
  checkpoint frequency: 100
  validation frequency: 5
  learning rate: 1e-4
  scheduler type: null
  # accepts null, exponential, reduce on plateau

loss:
  debug: regs only
  weights:
    relation sparsity: 1.
    relation smooth: 1.

network:
  type: relnet only
  output semantic: Gaussian likelihood
  relation kernel size: 7
  number of relations: 3

tags:
  - debug
random seed: 0
fixed input size: True