paths:
  path to initial model weights: null

data loading:
  dataset: pixels
  batch size: 64

optimizer:
  epochs: 1000
  checkpoint frequency: 10
  validation frequency: 10
  learning rate: 5e-5
  scheduler type: null
  # accepts null, exponential, reduce on plateau

loss: null

network:
  type: unet
  channels by depth: 1,64,64,N_L
  kernels by depth: 3,1,3
  pool depths: []

tags:
  - baseline
random seed: 0
fixed input size: True