paths:
  path to initial model weights: null

data loading:
  dataset: pixels
  batch size: 64

optimizer:
  epochs: 1000
  checkpoint frequency: 100
  validation frequency: 10
  G learning rate: 5e-5
  relnet learning rate: 5e-5
  scheduler type: null
  # accepts null, exponential, reduce on plateau

loss:
  weights:
    relation sparsity: .1
    relation smooth: .1
    relation score: .05
    cross entropy: 1.
  ramp epochs:
    relation score: 1000

network:
  type: vanilla
  output semantic: Gaussian likelihood
  relation kernel size: 9
  number of relations: 2
  segmenter architecture:
    channels by depth: 1,64,64,N_L
    kernels by depth: 3,1,3
    pool depths: []

random seed: 0
fixed input size: True